### ISSUE TITLE
When executing the script, I encountered the following error. May I ask whether the 'REL' package is custom or a third-party？ But the 'REL' package was installed in my virtual environment.

### ISSUE THREAD

**Issue by half-fairy** [gchochla/VAuLT#4]
/mm/VAuLT$ ./scripts/test-results.sh -t /data/twitter-tmsc -b /data/bloomberg-twitter-text-image -m /data/mvsa -c 0 -r 5
2023-03-19 08:57:38.432928: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
File "experiments/clsf_vault.py", line 8, in
from vault.models.vault import (
File "/home/wy/wy/mm/VAuLT/vault/models/vault/init.py", line 1, in
from .dataset import (
File "/home/wy/wy/mm/VAuLT/vault/models/vault/dataset.py", line 9, in
from vault.tmsc_utils.dataset import Twitter201XDataset, Twitter201XInfo
File "/home/wy/wy/mm/VAuLT/vault/tmsc_utils/dataset.py", line 16, in
from vault.entity_linking import EntityLinker
File "/home/wy/wy/mm/VAuLT/vault/entity_linking.py", line 7, in
from REL.ner import load_flair_ner, Cmns
ModuleNotFoundError: No module named 'REL'
![image](https://user-images.githubusercontent.com/58975392/226148806-c58cb965-4e4c-47b1-9495-c9946e225e62.png)
![image](https://user-images.githubusercontent.com/58975392/226148809-06eacfc8-9a06-4972-b1af-94e9baf82248.png)

**Comment by gchochla** [comment]
The REL package is installed by `setup.py`, and is different from the one install by `pip install REL` to my understanding. Please make sure to use the installation instructions on the README instead of installing everything manually using `pip`, and that you are using the current version of this repo. There is no need in that case to append paths for Python to find your packages, etc.

**Comment by half-fairy** [comment]
alright, thank you very much
